**Ojectives:**

1) Acquire an understanding of the different flavors/techniques for making recommendations 

2) Utilize Matrix Factorization to estimate/predict missing user ratings
 
3) Measure Recommendation Accuracy

### Objective 1: Acquire an understanding of the different flavors/techniques for making recommendations

**1)** **Content-based Recommendations** i.e. recommend products/items based on the attibutes of the product/item

Content-based recommendation engines utilize their knowledge of the attibutes of each product/item to recommend new products/items. 

Let's say that you inform your colleague at work that you just watched the movie **Rock** starring *Nicholas Cage* and that you really liked the movie. Based on this information, your colleague might recommend that you watch the movie **Con Air** next. Both movies are Action-packed Thrillers and both movies feature the same movie star. It could be a good recommendation because the movies have a few attributes in common. This is the fundamental idea behind content-based recommendation engines. Content-based recommendation engines recommend products that have similar attributes to a product that the user already liked.

**Point to Note**: Content-based recommendations can be effective only if you have *descriptive data* available for each product/item that you want to recommend. However, creating detailed information for each product/item in your inventory is not only a time-consuming process but it also introduces a fair degree of subjectivity that can throw off your recommendation results.

**2)** **Collaborative Filtering** i.e. recommend products solely based on user ratings

Collaborative filtering recommendation engines generate recommendations solely based on how users rated products in the past; it only possesses knowledge on how other users rated the product and it uses those past ratings to make new recommendations.

Let's say that **Thomson** has rated the following movies:

Rock: 5-Star

Con Air: 5-Star

Finding Nemo: 2-Star

Kubo and the 2 Strings: 1-Star


**Caleb** has given the following ratings to the movies:

Rock: 5 Star

Con Air: (No Rating)

Finding Nemo: 2-Star

Kubo and the 2 Strings: (No Rating)


**Aaron** has given the following ratings to the movies:

Rock: 2 Star

Con Air: 1 Star

Finding Nemo: 5-Star

Kubo and the 2 Strings: 4-Star

**Susanna** has given the following ratings to the movies:

Rock: 2 Star

Con Air: 1 Star

Finding Nemo: 5-Star

Kubo and the 2 Strings: 4-Star


Based on the user rating, a Collaborative filtering recommendation engine would recomend the movie "Con Air" to Caleb since Thomson and Caleb seem to have similar tastes.

**Collaborative filtering **has an advantage over content-based recommendations. Once you have user review data, you can build a collaborative filtering recommendation system. No knowledge about the attributes of the products/items being recommended is required. However if there is no information on user reviews/ratings, recommendations cannot be made.

**Some limitations of Collaborative Filtering:**

Collaborative Filtering only works when you already have user reviews to work from. If you do not have any reviews, you cannot make recommendations. Also, collaborative filtering tends to favor items with lots of reviews over items with few reviews. This can make it difficult for users to uncover new releases since they are not likely to get recommended as often.




### Objective 2: Utilize Matrix Factorization to estimate/predict missing user ratings

To develop a framework for making recommendations, we will walk-through an example:

**Goal**: Predict missing user ratings so that recommendations about similar products/items (i.e. movies for the purposes of this example) can be made

**Available Data**: **a)** User ratings for movies, **b)** List of movie titles and the respective genres

**Process**: In order to compute missing user ratings, we need 2 key pieces of information:

1) the user preferences across a range of attributes (the attributes could encompass Action, Comedy, Romance, Horror, etc.) 

2) the ratings for *each* movie across the same set of attributes

We will utilize the "User ratings for movies" data set to factor out a "User Ratings" matrix as well as a "Movie Rating" matrix. Once we have the 2 pieces of information highlighted above, we will leverage the concepts of Linear Algebra (i.e. **Matrix Multiplication**) to arrive at a value for "User Movie Rating" for each movie across every user which will provide an estimate/prediction for the missing user ratings so that the appropriate recommendations can be surfaced to each user

**User Movie Ratings** = User Ratings (across attributes) **X** Movie Ratings (across the same set of attributes) 

*Point to note*: When computing the following matrices: User Ratings (across attributes) and the Movie Ratings (across attributes), we have no idea what each attribute/feature is. All we know is that each attribute/feature represents some characteristic that has attracted users to certain products/items (in this case movies). Since we are unsure of how to describe those characteristics in words, they are deemed as **latent** features. The word latent just means hidden. 



In [0]:
# Import the requisite packages
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


df = pd.read_csv('https://www.dropbox.com/s/4ec9l887mth6rep/movie_ratings.csv?raw=1')
print(df['userid'])
df.head()

0        1
1        1
2        1
3        1
4        1
5        1
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       3
14       3
15       3
16       3
17       3
18       3
19       4
20       4
21       4
22       4
23       4
24       4
25       5
26       5
27       5
28       5
29       5
      ... 
650     96
651     96
652     96
653     96
654     96
655     96
656     97
657     97
658     97
659     97
660     97
661     97
662     98
663     98
664     98
665     98
666     98
667     98
668     99
669     99
670     99
671     99
672     99
673     99
674    100
675    100
676    100
677    100
678    100
679    100
Name: userid, Length: 680, dtype: int64


userid  movieid  rating
0       1       28       4
1       1       26       4
2       1        9       4
3       1        1       4
4       1       14       4

In [0]:
# Transpose the dataset set so that the columns represent the individual movies
df_pivot = pd.pivot_table(df, index='userid', columns='movieid', aggfunc=np.max).fillna(0)
print(df_pivot)

        rating                                              ...             \
movieid     1    2    3    4    5    6    7    8    9    10 ...    25   26   
userid                                                      ...              
1          4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0 ...   0.0  4.0   
2          5.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
3          4.0  4.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
4          5.0  5.0  0.0  5.0  5.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
5          5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0 ...   0.0  0.0   
6          5.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
7          5.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
8          4.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0 ...   0.0  0.0   
9          5.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
10         4.0  0.0  4.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0 ... 

We will utilize ** Matrix Factorization** to arrive at the 2 matrices i.e. **a)** User Ratings (across attributes)** b) ** Movie Ratings (across attributes). Once we have the 2 matrices, we will compute the "dot" product of the 2 matrices to come up with an estimate/prediction for the  missing user ratings 

There are a few different variations of the "Matrix Factorization" implementation, we will use the code put together by Albert Yeung: http://www.quuxlabs.com/wp-content/uploads/2010/09/mf.py_.txt

The mathematics behind "Matrix Factorization" can be reviewed here: http://www.quuxlabs.com/blog/2010/09/matrix-factorization-a-simple-tutorial-and-implementation-in-python/#source-code

Another resource on the concepts of "Matrix Factorization": https://www.youtube.com/watch?v=o8PiWO8C3zs




In [0]:
#
# Created by Albert Au Yeung (2010)
#
# An implementation of matrix factorization
#

!pip install numba
from numba import jit

@jit
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001:
            break
    return P, Q.T

    100% |████████████████████████████████| 1.9MB 6.5MB/s 
    100% |████████████████████████████████| 15.8MB 2.9MB/s 


In [0]:
   # R     : a matrix to be factorized, dimension N x M
   # P     : an initial matrix of dimension N x K
   # Q     : an initial matrix of dimension M x K
   # K     : the number of latent features
   # steps : the maximum number of steps to perform the optimization
   # alpha : the learning rate
   # beta  : the regularization parameter  
    R = df_pivot.as_matrix()
    N = len(R)
    M = len(R[0])
    K = 2

    P = np.random.rand(N,K) # Matrix of user attributes
    Q = np.random.rand(M,K) # Matrix of movie attributes

    nP, nQ = matrix_factorization(R, P, Q, K)

In [0]:
# User Movie Ratings = User Ratings (across attributes) **X** Movie Ratings (across the same set of attributes) 

nR = np.dot(nP, nQ.T)

print(nR) # Estimate/Prediction for the user movie ratings

#print(nP)

#print(nQ)


[[4.16949426 4.00094755 4.38628723 ... 3.93984333 3.63661991 3.50775916]
 [4.75419792 4.73640583 4.9381229  ... 4.16857892 3.90554048 4.18568233]
 [4.21311097 4.02060268 4.44022549 ... 4.02226999 3.70534666 3.52077514]
 ...
 [5.74591861 5.82458651 5.9318675  ... 4.85216774 4.58176744 5.16566103]
 [4.05492735 4.14191961 4.17473294 ... 3.36576601 3.18987085 3.67901065]
 [4.24223539 4.40741402 4.34066666 ... 3.38354395 3.2346989  3.92806678]]


array([4., 0., 0., 0., 0., 0., 0., 0., 4., 0., 0., 0., 5., 4., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 4., 0., 4., 0., 0., 0., 0., 0., 0.])

### Objective 3: Measure Recommendation Accuracy

To measure the accuracy of estimated "User Movie Ratings" , we will use a  statistical metric called root-mean-square-error (RMSE). RMSE is a meaure of the difference between the user's *actual *movie ratings and the ratings that were predicted for the same movies. 

The lower the root-mean-square-error, the more accurate the model. A root-mean-square-error of zero means our model perfectly estimates user ratings. If the root-mean-square-error for the test set is much higher than that of the training set, it is likely that you may have overfitted the data. In this example scenario, we are off by about one rating star on average when predicting user ratings.

We could adjust the **regularization** amount parameter to improve the accuracy of the recommendations. Regularization limits the amount of weight we place on a single attribute when finding user/item features with matrix factorization. The higher we set the regularization amount, the less weight we put on any single attribute. When you are building a recommendation engine, you will want to experiment with different regularization values to see how it affects the quality of your recommendations.

**Note**: One limitation that we faced in this example scenario is that we only had a few hundred movie reviews to work with; the best thing that could be done to improve accuracy in this case is to get more user reviews. More movie reviews will give our engine more information to work with so it can do a better job of making recommendations.





In [0]:
# Import the requisite packages
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Load user ratings
df_training = pd.read_csv('https://www.dropbox.com/s/ej76ujnyxmxn2mi/movie_ratings_training.csv?raw=1')
df_testing = pd.read_csv('https://www.dropbox.com/s/h5jwlmnaxu5xdvq/movie_ratings_testing.csv?raw=1')

# Convert the running list of user ratings into a matrix
df_training = pd.pivot_table(df_training, index='userid', columns='movieid', aggfunc=np.max)
df_testing = pd.pivot_table(df_testing, index='userid', columns='movieid', aggfunc=np.max)

R = df_training.as_matrix()
N = len(R)
M = len(R[0])
K = 2

P = np.random.rand(N,K) # Matrix of user attributes
Q = np.random.rand(M,K) # Matrix of movie attributes

nP, nQ = matrix_factorization(R, P, Q, K)

# Find all predicted ratings by multiplying nP and nQ 
   
nR = np.dot(nP, nQ.T)

# print(nR) # Estimate/Prediction for the user movie ratings

def RMSE(real, predicted):

  return np.sqrt(np.nanmean(np.square(real - predicted)))

# Measure RMSE
training_rmse = RMSE(df_training.as_matrix(), nR)
testing_rmse = RMSE(df_testing.as_matrix(), nR)

print("Training RMSE is: {}".format(training_rmse))
print("Testing RMSE is: {}".format(testing_rmse))

Training RMSE is: 0.607810674077778
Testing RMSE is: 1.193911645470413


**Additional Resources on Collaborative Filtering for your reference:** https://towardsdatascience.com/various-implementations-of-collaborative-filtering-100385c6dfe0

# Assignment

Write a function `recommend_for_user(user)` that takes a user and returns the top 5 recommended movies for them to watch that they have not already rated.

You should use the code from the lecture and coding challenge, and experiment with different approaches - you can use the predicted ratings we generated above, and you can experiment with different distance measurements or hybrid approaches (considering item similarity). You can also try an approach where e.g. you find the `n` users most similar to the given user, and average their preferences to generate new ratings and recommendations.

The end result should be a function that is reusable and suitable for an application and that satisfies this spec:

```
def recommend_for_user(user, n=5):
  """
  Generate movie recommendations for a user.
  Input: userId (from MovieLens data)
  Output: list of tuples (movieId, predictedRating) of top n movies recommended for user (not previously rated by them)
  """
  pass
```

As a stretch goal, prepare the data such that you generate test data - get a subset of users and drop some of their top ratings (favorite movies), then generate recommendations for them and see if they get recommended those movies and at what rating.

Part of the goal here is to think about making your code general and reusable, so it could plug into an actual live recommendation system. As a super-stretch goal, you can explore popular Python web application frameworks - these are the tools used to build the back-end that exposes an API so data can be displayed to the user.

- http://flask.pocoo.org/ - popular minimal framework
- https://www.djangoproject.com/ - "industry-grade" framework (more complicated, includes more features)

In a real-world situation, your role in a team could be ensuring that the API endpoint for generating recommendations does what it should (so everyone else can build on it). In web application terminology, this means that some route (e.g. `/recommendations/<user>`) can accept requests and return JSON data in response, essentially wrapping the function you built for this assignment.

In [0]:
def recommend_for_user(user):
  user_ratings = list(df_pivot.iloc[user-1].values)
  print(user_ratings)
  all_ratings = nR[user-1]
  print(all_ratings)
  seen = [i for i, e in enumerate(user_ratings) if e != 0]
  print('seen: ', seen)
  sorted_ix = sorted(range(len(all_ratings)), key=lambda k: all_ratings[k])
  print('sorted_ix: ', sorted_ix)
  sorted_unseen = [x for x in sorted_ix if x not in seen]
  print('sorted_unseen: ', sorted_unseen)
  rec = list(sorted_unseen)[-5:]
  return rec

print(recommend_for_user(1))
df.head()

[4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 5.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[4.16949426 4.00094755 4.38628723 4.48494697 4.54291464 4.16819384
 3.80186879 4.24308881 4.15864069 4.45835915 3.94217415 4.08909013
 4.21758252 4.05269627 3.0963399  3.88520256 2.60472788 3.15816033
 3.38061387 3.97707332 4.15196873 3.93745817 3.1504073  4.22236707
 4.41832625 4.20423269 4.15659528 4.15817776 2.90423789 3.76100816
 3.86695953 3.93984333 3.63661991 3.50775916]
seen:  [0, 8, 12, 13, 25, 27]
sorted_ix:  [16, 28, 14, 22, 17, 18, 33, 32, 29, 6, 30, 15, 21, 31, 10, 19, 1, 13, 11, 20, 26, 27, 8, 5, 0, 25, 12, 23, 7, 2, 24, 9, 3, 4]
sorted_unseen:  [16, 28, 14, 22, 17, 18, 33, 32, 29, 6, 30, 15, 21, 31, 10, 19, 1, 11, 20, 26, 5, 23, 7, 2, 24, 9, 3, 4]
[2, 24, 9, 3, 4]


userid  movieid  rating
0       1       28       4
1       1       26       4
2       1        9       4
3       1        1       4
4       1       14       4